---
- name: KWin | Apply KWin Activity Definitions | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_activity_config_file }}"
    values:
      - group: "{{ kwin_activity_group }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.name }}"
      - groups: "{{ kwin_activity_description_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.description }}"
      - groups: "{{ kwin_activity_icon_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.icon }}"
    backup: true
  loop: "{{ kwin_activities | dict2items }}"

# - name: KWin | Apply KWin Window Rules | kdeconfig
#   community.general.kdeconfig:
#     path: "{{ kwin_rules_config_file }}"
#     # values:
#     #   - group: "{{ item.value.group }}"
#     #     key: "{{ item.value.uuid }}"
#     #     value: "{{ item.value.name }}"
#     values: >
#       {{
#         kwin_rules | dict2items |
#         map('dict', {'group': item.value.group,
#                      'key': item2.key,
#                      'value': item2.value}) |
#         selectattr('key', 'ne', 'group') |
#         map('json_query', '[].{group: group, key: key, value: value}') |
#         flatten(1)
#       }}
#     backup: true
#   # loop: "{{ kwin_rules | dict2items }}"

- name: KWin | Apply KWin Window Rules | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values: >
      {{
        kwin_rules | dict2items |
        map('combine', {'group': item.value.group,
                       'key': item.key,
                       'value': item.value}) |
        selectattr('key', 'ne', 'group') |
        map('json_query', '[].{group: group, key: key, value: value}') |
        flatten(1)
      }}
    backup: true

- name: KWin | Apply KWin Window Rules(General Section) | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values:
      - group: General
        key: count
        value: "{{ kwin_rules | length }}"
      - group: General
        key: rules
        value: "{{ kwin_rules | dict2items | map(attribute='value.group') | join(',') }}"
    backup: true
