---
- name: KWin | Apply KWin Activity Definitions | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_activity_config_file }}"
    values:
      - group: "{{ kwin_activity_group }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.name }}"
      - groups: "{{ kwin_activity_description_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.description }}"
      - groups: "{{ kwin_activity_icon_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.icon }}"
    backup: true
  loop: "{{ kwin_activities | dict2items }}"

- name: KWin | Apply KWin Window Rules | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values: >
      {%- set rules_list = [] -%}
      {%- for rule in kwin_rules.values() -%}
        {%- set grp = rule.group -%}
        {%- for key, val in rule.items() if key != 'group' -%}
          {%- set _ = rules_list.append({'group': grp, 'key': key, 'value': val}) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ rules_list }}
    backup: true

- name: KWin | Apply KWin Window Rules(General Section) | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values:
      - group: General
        key: count
        value: "{{ kwin_rules | length }}"
      - group: General
        key: rules
        value: "{{ kwin_rules | dict2items | map(attribute='value.group') | join(',') }}"
    backup: true
