---
- name: KWin | Apply KWin Activity Definitions | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_activity_config_file }}"
    values:
      - group: "{{ kwin_activity_group }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.name }}"
      - groups: "{{ kwin_activity_description_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.description }}"
      - groups: "{{ kwin_activity_icon_subgroup }}"
        key: "{{ item.value.uuid }}"
        value: "{{ item.value.icon }}"
    backup: true
  loop: "{{ kwin_activities | dict2items }}"

- name: KWin | Apply KWin Window Rules | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values: >
      {%- set rules_list = [] -%}
      {%- for entry in kwin_rules.values() -%}
        {%- set rule = entry.kwin_rule -%}
        {%- set grp = rule.group -%}
        {%- for key, val in rule.items() if key != 'group' -%}
          {%- set _ = rules_list.append({'group': grp, 'key': key, 'value': val}) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ rules_list }}
    backup: true

- name: KWin | Apply KWin Window Rules(General Section) | kdeconfig
  community.general.kdeconfig:
    path: "{{ kwin_rules_config_file }}"
    values:
      - group: General
        key: count
        value: "{{ kwin_rules | length }}"
      - group: General
        key: rules
        value: "{{ kwin_rules | dict2items | map(attribute='value.kwin_rule.group') | join(',') }}"
    backup: true

- name: Plasma | Panel favorites per activity | kdeconfig
  community.general.kdeconfig:
    path: "{{ kde_plasma_config_file }}"
    values: >
      {# Target Task Manager applet General groups as nested tokens. #}
      {%- set groups_tokens = kde_panel_fav_groups
            | default([['Containments','2','Applets','5','Configuration','General']]) -%}

      {# Build activity -> [desktop ids] map from kwin_rules using icon. #}
      {%- set favs = {} -%}
      {%- for _name, entry in kwin_rules.items() -%}
        {%- set icon = entry.icon | default('') -%}
        {%- if icon|length > 0 -%}
          {%- set rule = entry.kwin_rule -%}
          {%- set parts = icon.split(' ') -%}
          {%- set base = rule.desktop
                        | default(parts[1] if (parts|length > 1 and ('.' in parts[1])) else parts[0]) -%}
          {%- set desktop = base ~ '.desktop' -%}
          {%- set act = rule.activity -%}
          {%- if act in favs -%}
            {%- if desktop not in favs[act] -%}
              {%- set _ = favs[act].append(desktop) -%}
            {%- endif -%}
          {%- else -%}
            {%- set _ = favs.update({ (act): [desktop] }) -%}
          {%- endif -%}
        {%- endif -%}
      {%- endfor -%}

      {# Compose launchers tokens and newline-separated value. #}
      {%- set tokens = [] -%}
      {%- for act in (favs.keys() | list | sort) -%}
        {%- for app in (favs[act] | sort) -%}
          {%- set _ = tokens.append('[' ~ act ~ ']\napplications:' ~ app) -%}
        {%- endfor -%}
      {%- endfor -%}

      {# Emit entries for each target group using nested `groups`. #}
      {%- set result = [] -%}
      {%- for grp in groups_tokens -%}
        {%- set val = (tokens | join(',')) -%}
        {%- set _ = result.append({'groups': grp, 'key': 'launchers', 'value': val}) -%}
      {%- endfor -%}
      {{ result }}
    backup: true
