---
system_home: "/home"
immutable_system_home: "/var/home"
install_languages: []
dotfiles_user_home: "{{ ansible_env.HOME }}"
default_home_local: "{{ dotfiles_user_home }}/.local"
tool_install_dir: "{{ default_home_local }}"
tool_install_bin: "{{ tool_install_dir }}/bin"
tool_system_path: "{{ tool_install_bin }}/"
bin_directory: "{{ tool_install_bin }}/"
xdg_share_dir: "{{ default_home_local }}/share"
xdg_config_dir: "{{ dotfiles_user_home }}/.config"
xdg_cache_dir:  "{{ dotfiles_user_home }}/.cache"
xdg_config_dirs:
  share: "{{ xdg_share_dir }}"
  config: "{{ xdg_config_dir }}"
  cache: "{{ xdg_cache_dir }}"
macos_config_dir: "{{ dotfiles_user_home }}/Library/Application\ Support"
dot_download_dir: "{{ tool_install_dir }}/downloads"
github_url: "https://github.com"
github_ssh_url: "ssh://git@github.com"
codeberg_url: "https://codeberg.org"
gcc_exe: /usr/bin/gcc
gpp_exe: /usr/bin/g++
make_exe: "make"
direnv_exe: "{{ tool_system_path }}direnv"
just_exe: "{{ tool_system_path }}just"
nu_exe: "nu"
fzf_path: "{{ fzf_install_dir }}/bin"
interactive_shell_cmd: "nu"
interactive_shell: "{{ nu_exe }}"
command_shell: "/bin/bash"
