---
- name: Install Tools
  hosts: localhost
  connection: local
  tasks:
    - import_role:
        name: devbox
      tags:
        - install
        - devbox

- name: Install Tools
  hosts: localhost
  connection: local
  tasks:
    - import_role:
        name: homebrew
      tags:
        - install
        - homebrew

- name: Install Tools
  hosts: localhost
  connection: local
  tasks:
    - import_role:
        name: nonroot
      tags:
        - install
        - nonroot

- name: Configure Environment
  hosts: localhost
  connection: local
  vars:
    tool_provider: "{{ lookup('env', 'TOOL_PROVIDER') }}"
  tasks:
    - import_role:
        name: dotfiles
