---
- name: Install Tools(Devbox)
  hosts: localhost
  vars_files:
    - vars/local.yml
  tasks:
    - import_role:
        name: devbox
      when: tool_provider == 'devbox'
      tags:
        - install

- name: Install Tools(Homebrew)
  hosts: localhost
  vars_files:
    - vars/local.yml
  tasks:
    - import_role:
        name: homebrew
      when: tool_provider == 'homebrew'
      tags:
        - install

- name: Install Tools(Non-Root)
  hosts: localhost
  vars_files:
    - vars/local.yml
  tasks:
    - import_role:
        name: nonroot
      when: tool_provider == 'nonroot'
      tags:
        - install

- name: Configure Environment
  hosts: localhost
  vars_files:
    - vars/local.yml
  vars:
    tool_provider: "{{ lookup('env', 'TOOL_PROVIDER') }}"
  tasks:
    - import_role:
        name: dotfiles
