---
- name: Lazygit | Setup Lazygit Config Directory | file
  file:
    path: "{{ lazygit_config }}"
    state: directory
    mode: "0755"

- name: Lazygit | Copies Lazygit Config | template
  template:
    src: lazygit/config.yml.j2
    dest: "{{ lazygit_config_file }}"
