---
- name: Vars | Set Devbox Variables | set_fact
  ansible.builtin.set_fact:
    bash_devbox_env: "eval \"$(devbox global shellenv --init-hook)\""
    zsh_devbox_env: |
      #. /home/{{ zsh_username }}/.nix-profile/etc/profile.d/nix.sh
      #. /home/{{ zsh_username }}/.nix-profile/etc/profile.d/hm-session-vars.sh
      export PATH=$PATH:{{ devbox_nix_root_path }}
      # export LANG=C.UTF-8
      # export LC_CTYPE=en_US.UTF-8
      # export LC_ALL=en_US.UTF-8
      export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive
      # export LANG=en_US.UTF-8
      export LANG=C.UTF-8
      export LC_CTYPE=C.UTF-8
      if  command -v devbox &> /dev/null
      then
        eval "$(devbox global shellenv --init-hook)"
      fi
    nu_devbox_env: |
      $env.PATH = ($env.PATH | split row (char esep) | append '{{ devbox_nix_root_path }}')
    direnv_exe: "direnv"
    just_exe: "just"
