---
- name: Ollama | Check for Ollama command | command
  command: "which {{ ollama_cmd }}"
  register: ollama_installed
  ignore_errors: true
  changed_when: false

- name: Ollama | Download Ollama Installer | get_url
  get_url:
    url: "{{ ollama_linux_installer }}"
    dest: "{{ ollama_installer_download_path }}"
    mode: 'u+rwx'
  when: ollama_installed.rc == 1
  register: download

- name: Ollama | Run the Installer | shell
  shell: "{{ ollama_installer_download_path }}"
  when: download.changed

- name: Ollama | Download Ollama Installer(ROCM) | get_url
  get_url:
    url: "{{ ollama_linux_installer_rocm }}"
    dest: "{{ ollama_installer_download_path_rocm }}"
    mode: 'u+rwx'
  when: rocm_support == true

- name: Ollama | Install Ollama ROCM Libraries | unarchive
  unarchive:
    src: "{{ ollama_installer_download_path_rocm }}"
    dest: "{{ ollama_installer_path_rocm }}"
  when: rocm_support == true

- name: Ollama | Remove the Installer | file
  file:
    path: "{{ ollama_installer_download_path }}"
    state: absent

- name: Ollama | Create Ollama System User | user
  user:
    name: ollama
    system: yes
    create_home: yes
    home: /usr/share/ollama
    shell: /bin/false
    state: present

- name: Ollama | Add Current User to Ollama Group | user
  user:
    name: "{{ ansible_env.USER }}"
    groups: ollama
    append: yes

- name: Ollama | Install SystemD Service File | template
  ansible.builtin.template:
    src: "{{ ollama_service_filename }}.j2"
    dest: "{{ ollama_service_install_location }}"

- name: Ollama | Reload Systemd Daemon | systemd
  systemd:
    daemon_reload: yes

- name: Ollama | Enable ollama service | systemd
  systemd:
    name: ollama
    state: started
    enabled: yes
