---
- name: Code2Prompt | Check if pipx is installed | command
  command: which pipx
  register: pipx_installed
  ignore_errors: true
  changed_when: false

- name: Code2Prompt | Install Code2Prompt | command
  command: pipx install code2prompt
  when: pipx_installed.rc == 0
  changed_when: false

- name: Code2Prompt | Install LLM | command
  command: pipx install llm
  when: pipx_installed.rc == 0
  changed_when: false

# - name: Code2Prompt | Install Code2Prompt | pipx
#   community.general.pipx:
#     name: code2prompt
#     state: latest

- name: Code2Prompt | Setup Code2Prompt Templates Directory | file
  file:
    path: "{{ code2prompt_template_dir }}"
    state: directory
    mode: "0755"

- name: Code2Prompt | Copies Code2Prompt Config | template
  vars:
    code2prompt_template: "{{ item.value.template }}"
  template:
    src: code2prompt.j2
    dest: "{{ code2prompt_template_dir }}/{{ item.value.name }}"
  loop: "{{ code2prompt_templates | dict2items }}"

- name: Code2Prompt | Copies Code2Prompt Config | file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ code2prompt_template_dir }}/{{ item.path  | regex_replace('\\.md$', '') }}"
  with_filetree: '../files/code2prompt_templates'
  when: item.state == 'file'
