---
- name: Code2Prompt | Check if pipx is installed | command
  command: which pipx
  register: pipx_installed
  ignore_errors: true
  changed_when: false

- name: Code2Prompt | Install Code2Prompt | command
  command: pipx install code2prompt
  when: pipx_installed.rc == 0
