---
ollama_linux_installer: "https://ollama.com/install.sh"
ollama_installer_download_path: "{{ dot_download_dir }}/ollama-installer.sh"
ollama_macos_installer: "https://ollama.com/download/Ollama-darwin.zip"
ollama_macos_installer_download_path: "{{ dot_download_dir }}/Ollama-darwin"
ollama_macos_app_name: "Ollama.app"
ollama_macos_app: "{{ ollama_macos_installer_download_path }}/{{ ollama_macos_app_name }}"
ollama_cmd: "ollama"
