---
ollama_linux_installer: "https://ollama.com/install.sh"
ollama_linux_installer_rocm: "https://ollama.com/download/ollama-linux-amd64-rocm.tgz"
ollama_installer_download_path: "{{ dot_download_dir }}/ollama-installer.sh"
ollama_installer_download_rocm: "ollama-linux-amd64-rocm"
ollama_installer_download_path_rocm: "{{ dot_download_dir }}/{{ ollama_installer_download_rocm }}.tgz"
ollama_installer_path_rocm: "/usr"
ollama_macos_installer: "https://ollama.com/download/Ollama-darwin.zip"
ollama_macos_installer_download_path: "{{ dot_download_dir }}/Ollama-darwin"
ollama_macos_app_name: "Ollama.app"
ollama_macos_app: "{{ ollama_macos_installer_download_path }}/{{ ollama_macos_app_name }}"
ollama_macos_app_exe: "/Applications/{{ ollama_macos_app_name }}"
ollama_cmd: "ollama"
ollama_exe: "/usr/local/bin/{{ ollama_cmd }}"
ollama_service_filename: "ollama.service"
ollama_service_install_location: "/etc/systemd/system/{{ ollama_service_filename }}"
rocm_support: false
