---
bin_directory: "{{ ansible_env.HOME }}/.local/bin"
nix_bin: "{{ ansible_env.HOME }}/.nix-profile/bin"
homebrew_install_path: "/home/linuxbrew/.linuxbrew"
homebrew_path: "{{ homebrew_install_path }}/bin"
pipx_exe: "{{ bin_directory }}/pipx"
brew_pipx_exe: "{{ homebrew_path }}/pipx"
devbox_exe: "/usr/local/bin/devbox"
devbox_kde_tools:
  - konsave
  - kde-cli-tools
xdg_config_dir: "{{ ansible_env.HOME }}/.config"
kde_plasma_config_file: "{{ xdg_config_dir }}/plasma-org.kde.plasma.desktop-appletsrc"
kwin_activity_config_file: "{{ xdg_config_dir }}/kactivitymanagerdrc"
kwin_activity_group: "activities"
kwin_activity_description_subgroup: "{{ kwin_activity_group }}-descriptions"
kwin_activity_icon_subgroup: "{{ kwin_activity_group }}-icons"
kwin_activities:
  browse:
    name: "Browse"
    description: "Web Browse & Research"
    icon: "com.opera.Opera"
    uuid: "240d6a84-dda7-4e1f-9e0c-ab1a9585d939"
  obsidian:
    name: "Obsidian"
    description: "Obsidian Notes"
    icon: "md.obsidian.Obsidian"
    uuid: "4156f55c-e8dc-4f82-b46f-d91bb348073f"
  office:
    name: "Office"
    description: "Office Applications"
    icon: "org.onlyoffice.desktopeditors"
    uuid: "5a0e58a4-8df1-4f16-a081-a6a1e28da7da"
  code:
    name: "Code"
    description: "Developer Environment"
    icon: "com.visualstudio.code.oss"
    uuid: "daeb040e-07f4-46fe-9266-69fc8f3f6cbb"
  calc:
    name: "Calculator"
    description: "Calculator"
    icon: "org.kde.kalgebra"
    uuid: "3d98f125-ee0a-4368-8150-9cbed439f27a"
  vault:
    name: "Vault"
    description: "The Vault"
    icon: "com.bitwarden.desktop"
    uuid: "2397e318-eec7-4c4b-b114-6c2dec42961a"
  system:
    name: "System"
    description: "Manage Local System"
    icon: "systemsettings"
    uuid: "1d5d08f2-bbf1-4993-9cc4-6b49e775858b"
kwin_rules_web_5k_left_23:
  position: "48,4"
  size: "994,1481"
kwin_rules_web_5k_right_23:
  position: "1045,4"
  size: "2484,1481"
kwin_rules_code_5k_left_23:
  position: "48,4"
  size: "799,1481"
kwin_rules_code_5k_right_23:
  position: "850,4"
  size: "2679,1481"
kwin_rules_singlefloat_5k:
  position: "843,177"
  size: "1700,1047"
kwin_rules_fw13_full:
  position: "0,0"
  size: "1128,708"
kwin_rules_web_left_23: "{{ kwin_rules_web_5k_left_23 }}"
kwin_rules_web_right_23: "{{ kwin_rules_web_5k_right_23 }}"
kwin_rules_code_left_23: "{{ kwin_rules_code_5k_left_23 }}"
kwin_rules_code_right_23: "{{ kwin_rules_code_5k_right_23 }}"
kwin_rules_calc_left_23: "{{ kwin_rules_web_5k_left_23 }}"
kwin_rules_calc_right_23: "{{ kwin_rules_web_5k_right_23 }}"
kwin_rules_singlefloat: "{{ kwin_rules_singlefloat_5k }}"
kwin_rules_config_file: "{{ xdg_config_dir }}/kwinrulesrc"
kwin_rules:
  brave:
    icon: "com.brave.Browser"
    kwin_rule:
      group: "207e083a-eb97-47f1-81ef-172cc820c3c2"
      Description: "Brave: Browser"
      wmclass: "Brave-browser"
      activity: "{{ kwin_activities['browse']['uuid'] }}"
      position: "{{ kwin_rules_web_right_23['position'] }}"
      size: "{{ kwin_rules_web_right_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  opera:
    icon: "com.opera.Opera"
    kwin_rule:
      group: "3c93494e-08c5-4fba-a3b8-1dacfa6d1d36"
      Description: "Opera: Browser"
      wmclass: "Opera"
      activity: "{{ kwin_activities['browse']['uuid'] }}"
      position: "{{ kwin_rules_web_right_23['position'] }}"
      size: "{{ kwin_rules_web_right_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  thunderbird:
    icon: "org.mozilla.Thunderbird"
    kwin_rule:
      group: "6d7f8fa9-b0ef-4ed7-9832-2c223e2a78df"
      Description: "Thunderbird: Email"
      wmclass: "org.mozilla.Thunderbird"
      activity: "{{ kwin_activities['browse']['uuid'] }}"
      position: "{{ kwin_rules_web_left_23['position'] }}"
      size: "{{ kwin_rules_web_left_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  obsidian:
    icon: "md.obsidian.Obsidian"
    kwin_rule:
      group: "4f2d124b-584c-43a0-871c-e991d278e733"
      Description: "Obsidian"
      wmclass: "obsidian obsidian"
      activity: "{{ kwin_activities['obsidian']['uuid'] }}"
      position: "{{ kwin_rules_singlefloat['position'] }}"
      size: "{{ kwin_rules_singlefloat['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  onlyoffice:
    icon: "org.onlyoffice.desktopeditors"
    kwin_rule:
      group: "640d19cd-76ad-4a12-af14-5fd029dfc6a1"
      Description: "OnlyOffice"
      wmclass: "ONLYOFFICE"
      activity: "{{ kwin_activities['office']['uuid'] }}"
      position: "{{ kwin_rules_singlefloat['position'] }}"
      size: "{{ kwin_rules_singlefloat['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  boxbuddy:
    icon: "io.github.dvlv.boxbuddyrs"
    kwin_rule:
      group: "e3f3d994-d791-4169-9d02-0a9d248f1062"
      Description: "BoxBuddy"
      wmclass: "io.github.dvlv.boxbuddyrs"
      activity: "{{ kwin_activities['code']['uuid'] }}"
      position: "{{ kwin_rules_code_left_23['position'] }}"
      size: "{{ kwin_rules_code_left_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  ptyxis:
    icon: "app.devsuite.Ptyxis"
    kwin_rule:
      group: "e766885e-ddb4-4760-918b-1be22196dca0"
      Description: "Ptyxis"
      wmclass: "app.devsuite.Ptyxis"
      activity: "{{ kwin_activities['code']['uuid'] }}"
      position: "{{ kwin_rules_code_right_23['position'] }}"
      size: "{{ kwin_rules_code_right_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  konsole:
    icon: "org.kde.konsole"
    kwin_rule:
      group: "f6e336a0-f275-4c1f-99ca-ee8d9ecbbe87"
      Description: "Konsole"
      wmclass: "org.kde.konsole"
      activity: "{{ kwin_activities['code']['uuid'] }}"
      position: "{{ kwin_rules_code_right_23['position'] }}"
      size: "{{ kwin_rules_code_right_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  kalgebra:
    icon: "org.kde.kalgebra"
    kwin_rule:
      group: "2d877772-e16e-449d-97e1-7e30f3ebc56c"
      Description: "KAlgebra"
      wmclass: "org.kde.kalgebra"
      activity: "{{ kwin_activities['calc']['uuid'] }}"
      position: "{{ kwin_rules_calc_left_23['position'] }}"
      size: "{{ kwin_rules_calc_left_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  kantor:
    icon: "org.kde.cantor"
    kwin_rule:
      group: "a4b3c7ff-8f00-4dcf-be9b-bff18dc95b50"
      Description: "Cantor"
      wmclass: "org.kde.cantor"
      activity: "{{ kwin_activities['calc']['uuid'] }}"
      position: "{{ kwin_rules_calc_right_23['position'] }}"
      size: "{{ kwin_rules_calc_right_23['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  qalculate:
    icon: "io.github.Qalculate"
    kwin_rule:
      group: "8e0b0873-aa0f-4598-a2e1-97bd712094b4"
      Description: "Qalculate"
      wmclass: "io.github.Qalculate"
      activity: "{{ kwin_activities['calc']['uuid'] }}"
      position: "{{ kwin_rules_singlefloat['position'] }}"
      size: "{{ kwin_rules_singlefloat['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  kdesettings:
    icon: "systemsettings"
    kwin_rule:
      group: "9f54c4ba-098c-48f5-b159-ddcf378803cc"
      Description: "KDE Settings"
      wmclass: "systemsettings systemsettings"
      activity: "{{ kwin_activities['system']['uuid'] }}"
      position: "{{ kwin_rules_singlefloat['position'] }}"
      size: "{{ kwin_rules_singlefloat['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
  bitwarden:
    icon: "com.bitwarden.desktop"
    kwin_rule:
      group: "d6077181-4635-4f2d-b29e-480e0884dffe"
      Description: "Bitwarden"
      wmclass: "Bitwarden"
      activity: "{{ kwin_activities['vault']['uuid'] }}"
      position: "{{ kwin_rules_singlefloat['position'] }}"
      size: "{{ kwin_rules_singlefloat['size'] }}"
      activityrule: "3"
      positionrule: "3"
      sizerule: "3"
      wmclassmatch: "2"
      ignoregeometry: "true"
      ignoregeometryrule: "3"
