---
bin_directory: "{{ ansible_env.HOME }}/.local/bin"
nix_bin: "{{ ansible_env.HOME }}/.nix-profile/bin"
homebrew_install_path: "/home/linuxbrew/.linuxbrew"
homebrew_path: "{{ homebrew_install_path }}/bin"
pipx_exe: "{{ bin_directory }}/pipx"
brew_pipx_exe: "{{ homebrew_path }}/pipx"
devbox_exe: "/usr/local/bin/devbox"
devbox_kde_tools:
  - konsave
  - kde-cli-tools
xdg_config_dir: "{{ ansible_env.HOME }}/.config"
kde_plasma_config_file: "{{ xdg_config_dir }}/plasma-org.kde.plasma.desktop-appletsrc"
kwin_activity_config_file: "{{ xdg_config_dir }}/kactivitymanagerdrc"
kwin_activity_group: "activities"
kwin_activity_description_subgroup: "{{ kwin_activity_group }}-descriptions"
kwin_activity_icon_subgroup: "{{ kwin_activity_group }}-icons"
kwin_activities:
  browse:
    name: "Browse"
    description: "Web Browse & Research"
    icon: "com.brave.Browser"
    uuid: "240d6a84-dda7-4e1f-9e0c-ab1a9585d939"
  code:
    name: "Code"
    description: "Developer Environment"
    icon: "com.visualstudio.code.oss"
    uuid: "daeb040e-07f4-46fe-9266-69fc8f3f6cbb"
  calc:
    name: "Calculator"
    description: "Calculator"
    icon: "org.kde.kalgebra"
    uuid: "3d98f125-ee0a-4368-8150-9cbed439f27a"
  vault:
    name: "Vault"
    description: "The Vault"
    icon: "bitwarden"
    uuid: "2397e318-eec7-4c4b-b114-6c2dec42961a"
  system:
    name: "System"
    description: "Manage Local System"
    icon: "systemsettings"
    uuid: "1d5d08f2-bbf1-4993-9cc4-6b49e775858b"
kwin_rules_web_5k_left_23:
  position: "48,4"
  size: "983,1432"
kwin_rules_web_5k_right_23:
  position: "1035,4"
  size: "2376,1432"
kwin_rules_code_5k_left_23:
  position: "48,4"
  size: "803,1432"
kwin_rules_code_5k_right_23:
  position: "855,4"
  size: "2554,1432"
kwin_rules_singlefloat_5k:
  position: "843,177"
  size: "1700,1047"
kwin_rules_web_left_23: "{{ kwin_rules_web_5k_left_23 }}"
kwin_rules_web_right_23: "{{ kwin_rules_web_5k_right_23 }}"
kwin_rules_code_left_23: "{{ kwin_rules_code_5k_left_23 }}"
kwin_rules_code_right_23: "{{ kwin_rules_code_5k_right_23 }}"
kwin_rules_calc_left_23: "{{ kwin_rules_web_5k_left_23 }}"
kwin_rules_calc_right_23: "{{ kwin_rules_web_5k_right_23 }}"
kwin_rules_singlefloat: "{{ kwin_rules_singlefloat_5k }}"
kwin_rules_config_file: "{{ xdg_config_dir }}/kwinrulesrc"
kwin_rules:
  brave:
    group: "207e083a-eb97-47f1-81ef-172cc820c3c2"
    Description: "Brave: Browser"
    wmclass: "Brave-browser"
    activity: "{{ kwin_activities['browse']['uuid'] }}"
    position: "{{ kwin_rules_web_right_23['position'] }}"
    size: "{{ kwin_rules_web_right_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  opera:
    group: "3c93494e-08c5-4fba-a3b8-1dacfa6d1d36"
    Description: "Opera: Browser"
    wmclass: "Opera"
    activity: "{{ kwin_activities['browse']['uuid'] }}"
    position: "{{ kwin_rules_web_right_23['position'] }}"
    size: "{{ kwin_rules_web_right_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  thunderbird:
    group: "6d7f8fa9-b0ef-4ed7-9832-2c223e2a78df"
    Description: "Thunderbird: Email"
    wmclass: "org.mozilla.Thunderbird"
    activity: "{{ kwin_activities['browse']['uuid'] }}"
    position: "{{ kwin_rules_web_left_23['position'] }}"
    size: "{{ kwin_rules_web_left_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  boxbuddy:
    group: "e3f3d994-d791-4169-9d02-0a9d248f1062"
    Description: "BoxBuddy"
    wmclass: "io.github.dvlv.boxbuddyrs"
    activity: "{{ kwin_activities['code']['uuid'] }}"
    position: "{{ kwin_rules_code_left_23['position'] }}"
    size: "{{ kwin_rules_code_left_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  konsole:
    group: "f6e336a0-f275-4c1f-99ca-ee8d9ecbbe87"
    Description: "Konsole"
    wmclass: "konsole org.kde.konsole"
    activity: "{{ kwin_activities['code']['uuid'] }}"
    position: "{{ kwin_rules_code_right_23['position'] }}"
    size: "{{ kwin_rules_code_right_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  kalgebra:
    group: "2d877772-e16e-449d-97e1-7e30f3ebc56c"
    Description: "KAlgebra"
    wmclass: "org.kde.kalgebra"
    activity: "{{ kwin_activities['calc']['uuid'] }}"
    position: "{{ kwin_rules_calc_left_23['position'] }}"
    size: "{{ kwin_rules_calc_left_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  kantor:
    group: "a4b3c7ff-8f00-4dcf-be9b-bff18dc95b50"
    Description: "Cantor"
    wmclass: "org.kde.cantor"
    activity: "{{ kwin_activities['calc']['uuid'] }}"
    position: "{{ kwin_rules_calc_right_23['position'] }}"
    size: "{{ kwin_rules_calc_right_23['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  kdesettings:
    group: "9f54c4ba-098c-48f5-b159-ddcf378803cc"
    Description: "KDE Settings"
    wmclass: "systemsettings systemsettings"
    activity: "{{ kwin_activities['system']['uuid'] }}"
    position: "{{ kwin_rules_singlefloat['position'] }}"
    size: "{{ kwin_rules_singlefloat['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"
  bitwarden:
    group: "d6077181-4635-4f2d-b29e-480e0884dffe"
    Description: "Bitwarden"
    wmclass: "Bitwarden"
    activity: "{{ kwin_activities['vault']['uuid'] }}"
    position: "{{ kwin_rules_singlefloat['position'] }}"
    size: "{{ kwin_rules_singlefloat['size'] }}"
    activityrule: "3"
    positionrule: "3"
    sizerule: "3"
    wmclassmatch: "2"
    ignoregeometry: "true"
    ignoregeometryrule: "3"

# [1c393591-2c43-456e-af2e-c0bfc1eaca25]
# Description=Konsole: Distrobox
# activity=736a6f29-365b-4ec1-960c-ec8f62689ed4
# activityrule=3
# position=841,4
# positionrule=3
# size=2229,1272
# sizerule=3
# title=~ : distrobox — Konsole
# titlematch=1
# wmclassmatch=1
#
# [2b73bb6d-2d58-49f5-9232-7fc4edbb041d]
# Description=Brave
# activity=12b9d29c-3bd4-4e5f-a32b-b42d353dd197
# activityrule=3
# position=1070,4
# positionrule=3
# size=1998,1272
# sizerule=3
# windowrole=browser
# windowrolematch=1
# wmclass=Brave-browser
# wmclassmatch=2
#
# [General]
# count=6
# rules=efae0029-a1b2-4432-9973-99a2ae368332,2b73bb6d-2d58-49f5-9232-7fc4edbb041d,c12627c0-d996-49e4-b197-b85ea40a5e51,b267b9f7-6b30-4091-8e26-c3fe3cca6ce1,be08951e-0ca7-496e-a943-1876532124b3,1c393591-2c43-456e-af2e-c0bfc1eaca25
#
# [b267b9f7-6b30-4091-8e26-c3fe3cca6ce1]
# Description=ChatGPT
# activity=736a6f29-365b-4ec1-960c-ec8f62689ed4
# activityrule=3
# position=1070,4
# positionrule=3
# size=1998,1272
# sizerule=3
# title=ChatGPT
# titlematch=2
# types=1
# windowrole=pop-up
# windowrolematch=2
# wmclass=Brave-browser
#
# [be08951e-0ca7-496e-a943-1876532124b3]
# Description=BoxBuddy
# activity=736a6f29-365b-4ec1-960c-ec8f62689ed4
# activityrule=3
# position=48,4
# positionrule=3
# size=1018,1272
# sizerule=3
# title=BoxBuddy
# wmclass=io.github.dvlv.boxbuddyrs
# wmclassmatch=1
#
# [c12627c0-d996-49e4-b197-b85ea40a5e51]
# Description=Thunderbird
# activity=12b9d29c-3bd4-4e5f-a32b-b42d353dd197
# activityrule=3
# position=48,4
# positionrule=3
# size=1018,1272
# sizerule=3
# wmclass=org.mozilla.Thunderbird
# wmclassmatch=2
#
# [efae0029-a1b2-4432-9973-99a2ae368332]
# Description=Window settings for org.wezfurlong.wezterm
# activity=736a6f29-365b-4ec1-960c-ec8f62689ed4
# activityrule=3
# position=831,4
# positionrule=3
# size=2239,1272
# sizerule=3
# title=Zellij (chipyard) - devbox run nvim
# types=1
# wmclass=\sorg.wezfurlong.wezterm
# wmclasscomplete=true
# wmclassmatch=1
