---
- name: ACP | Setup pnpm
  ansible.builtin.command: "{{ acp_pnpm_executable }} setup"
  args:
    creates: "{{ acp_pnpm_home }}"
  environment:
    PNPM_HOME: "{{ acp_pnpm_home }}"
    PATH: "{{ acp_pnpm_home }}/bin:{{ acp_pnpm_home }}:{{ ansible_facts['env']['PATH'] }}"

- name: ACP | Query pnpm global bin directory
  ansible.builtin.command: "{{ acp_pnpm_executable }} config get global-bin-dir"
  register: acp_pnpm_global_bin_dir
  changed_when: false
  environment:
    PNPM_HOME: "{{ acp_pnpm_home }}"
    PATH: "{{ acp_pnpm_home }}/bin:{{ acp_pnpm_home }}:{{ ansible_facts['env']['PATH'] }}"

- name: ACP | Install adapters
  community.general.pnpm:
    name: "{{ item }}"
    global: "{{ acp_pnpm_global }}"
    state: "{{ acp_pnpm_state }}"
    executable: "{{ acp_pnpm_executable }}"
    version: "{{ acp_pnpm_version | default(omit, true) }}"
  loop: "{{ acp_adapters }}"
  environment:
    PNPM_HOME: "{{ acp_pnpm_home }}"
    PATH: "{{ acp_pnpm_global_bin_dir.stdout }}:{{ acp_pnpm_home }}/bin:{{ acp_pnpm_home }}:{{ ansible_facts['env']['PATH'] }}"
