---
opencode_install_script_path: "{{ ansible_facts['env']['HOME'] }}/opencode-install.sh"
opencode_install_dir: "{{ ansible_facts['env']['HOME'] }}/.opencode"
opencode_path: "{{ opencode_install_dir }}/bin"
